name: dev-helm-chart
hostname: dev-helm-chart.local
environmentName: dev
image:
  repository: dev-helm-chart
ci:
  deploymentTag: dev
# In case migration image is set
#  deploymentMigrationTag: dev

servicePort: 80
containerPort: 8080
imagePullSecrets:
  - name: 'regcred'
replicas: 1
ingress:
  enabled: false
  acme: false
  acmeRegistrationEmail: nobody@localhost.local
  path: /
  tlsSecretName: dev-localhost-local-tls
  annotations:
    kubernetes.io/ingress.class: nginx
headlessService: false
metrics:
  enabled: false
  port: 1234
migration:
  enabled: false
#  image:
#    repository: sample-migration
  command:
    - echo
    - hello
    - world

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# Or set to empty {}
livenessProbe: {}
# Example:
#  exec:
#    command:
#    - cat
#    - /tmp/healthy
#  initialDelaySeconds: 5
#  periodSeconds: 5

# https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# Or set to empty {}
readinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

worker:
  enabled: false
  deploymentStrategy: RollingUpdate
  instances:
    - name: foo
      replicas: 1
      command:
        - echo
        - hello
        - world
    - name: bar
      replicas: 2
      resources: {}
      # resources:
      #     requests:
      #       cpu: 300m
      #       memory: 150Mi
      #     limits:
      #       cpu: 600m
      #       memory: 300Mi
      command:
        - echo
        - hello
        - world
      env:
        - name: FOO
          value: FUU
        - name: BAR
          value: BAZ
