name: dev-helm-chart
hostname: dev-helm-chart.local
environmentName: dev
image:
  repository: dev-helm-chart
ci:
  deploymentTag: dev

servicePort: 80
containerPort: 8080
imagePullSecrets:
  - name: 'regcred'
replicas: 1
ingress:
  enabled: false
  acme: false
  acmeRegistrationEmail: nobody@localhost.local
  path: /
  tlsSecretName: dev-localhost-local-tls
  annotations:
    kubernetes.io/ingress.class: nginx
migration:
  enabled: false
  command:
    - echo
    - hello
    - world

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

worker:
  enabled: false
  deploymentStrategy: RollingUpdate
  instances:
    - name: foo
      replicas: 1
      command:
        - echo
        - hello
        - world
    - name: bar
      replicas: 2
      command:
        - echo
        - hello
        - world
      env:
        - name: FOO
          value: FUU
        - name: BAR
          value: BAZ
