name: dev-helm-chart
hostname: dev-helm-chart.local
environmentName: dev
image:
  repository: dev-helm-chart
ci:
  deploymentTag: dev

servicePort: 8080
imagePullSecrets:
  - name: 'regcred'
replicas: 1
ingress:
  enabled: false
  acme: false
  acmeRegistrationEamil: nobody@localhost.local
  path: /
  tlsSecretName: dev-localhost-local-tls
migration:
     enabled: true
     command:
       - echo
       - hello
       - world
