name: dev-helm-chart
hostname: dev-helm-chart.local
environmentName: dev
image:
  repository: dev-helm-chart
ci:
  deploymentTag: dev

servicePort: 80
containerPort: 8080
imagePullSecrets:
  - name: 'regcred'
replicas: 1
ingress:
  enabled: false
  acme: false
  acmeRegistrationEmail: nobody@localhost.local
  path: /
  tlsSecretName: dev-localhost-local-tls
migration:
     enabled: true
     command:
       - echo
       - hello
       - world
worker:
  enabled: true
  instances:
    - name: foo
      replicas: 1
      command:
        - echo
        - hello
        - world
    - name: bar
      replicas: 2
      command:
        - echo
        - hello
        - world
      env:
        - name: FOO
          value: FUU
        - name: BAR
          value: BAZ
