{{- if .Values.ssl }}
{{- if (eq .Values.ssl.enabled true) }}
{{- $environment := .Values.environmentName -}}
{{- $lets_encrypt_name := include "hm-basic-webapp.letsEncryptProductionName" . }}
{{- range $item := .Values.ssl }}
{{- if eq $item.manual false }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ $environment }}-{{ $item.host | replace "." "-" }}-cert"
spec:
  secretName: "{{ $item.tlsSecretName }}"
  renewBefore: 360h # 15d
  commonName: {{ $item.host }}
  dnsNames:
    - {{ $item.host }}
  issuerRef:
    name: {{ $lets_encrypt_name }}
    kind: Issuer
{{- end }}
{{- end }}
{{- end }}
{{- end }}
