{{- if .Values.ingress }}
{{- if (eq .Values.ingress.enabled true) }}
{{- $environment := .Values.environmentName -}}
{{- $lets_encrypt_name := include "hm-basic-webapp.letsEncryptProductionName" . }}
{{- if eq .Values.ingress.acme true }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ $environment }}-{{ printf "%s-%s" .Values.name .Values.hostname | replace "." "-" }}-cert"
spec:
  secretName: "{{ .Values.ingress.tlsSecretName }}"
  renewBefore: 360h # 15d
  commonName: {{ .Values.hostname }}
  dnsNames:
    - {{ .Values.hostname }}
  issuerRef:
    name: {{ $lets_encrypt_name }}
    kind: Issuer
{{- end }}
{{- end }}
{{- end }}
