apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hm-basic-webapp.prefix" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "hm-basic-webapp.prefix" . }}
  template:
    metadata:
      labels:
        app: {{ include "hm-basic-webapp.prefix" . }}
        app.kubernetes.io/managed-by: {{.Release.Service }}
        app.kubernetes.io/instance: {{.Release.Name }}
      annotations:
        date: {{ now }}
    spec:
      imagePullSecrets:
        {{- .Values.imagePullSecrets | toYaml | nindent 8 }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.ci.deploymentTag | default .Chart.AppVersion }}"
          name: {{ include "hm-basic-webapp.prefix" . }}
          ports:
            - containerPort: {{ .Values.servicePort }}
          env:
            - name: K8S_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- $configName := include "hm-basic-webapp.configName" . -}}
            {{- range $name, $_value := .Values.configMapData }}
            - name: {{ $name }}
              valueFrom:
                configMapKeyRef:
                  key: {{ $name }}
                  name: {{ $configName }}
            {{- end }}
            {{- $secretName := include "hm-basic-webapp.secretName" . -}}
            {{- range $name, $_value := .Values.secretData }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  key: {{ $name }}
                  name: {{ $secretName }}
            {{- end }}
