{{- if .Values.ingress }}
{{- if (eq .Values.ingress.enabled true) }}
{{- $fullName := include "hm-basic-webapp.prefix" . }}
{{- $servicePort := .Values.servicePort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hm-basic-webapp.prefix" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.hostname | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}

  rules:
    - host: {{ .Values.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
{{- end }}
{{- end }}
