{{- if .Values.ingress }}
{{- if (eq .Values.ingress.enabled true) }}
{{- $fullName := include "hm-basic-webapp.prefix" . }}
{{- $servicePort := .Values.servicePort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hm-basic-webapp.prefix" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.hostname | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}

  rules:
    - host: {{ .Values.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
{{- end }}
{{- end }}
