{{- if .Values.ingress }}
{{- if and .Values.ingress.enabled .Values.ingress.acme  }}
{{- if not (eq .Values.environmentName "prod") }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 name: {{ include "hm-basic-webapp.letsEncryptStagingName" . }}
spec:
 acme:
   # The ACME server URL
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: {{ .Values.ingress.acmeRegistrationEamil }}
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: {{ include "hm-basic-webapp.letsEncryptStagingName" . }}
   # Enable the HTTP-01 challenge provider
   solvers:
   - http01:
       ingress:
         class: nginx
{{- end }}
{{- end }}
{{- end }}
