{{- if .Values.ssl }}
{{- if (eq .Values.ssl.enabled true) }}
{{- range $item := .Values.ssl }}
{{- if and $item.crt $item.key $item.manual }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: "{{ $item.name }}-tls"
data:
  tls.crt: {{ $item.crt }}
  tls.key: {{ $item.key }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
