{{- if .Values.ingress }}
{{- if (eq .Values.ingress.enabled true) }}
{{- if (eq .Values.ingress.acme false) }}
{{- range $item := .Values.ingress.tls }}
{{- if and $item.crt $item.key }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: "{{ $item.name }}-tls"
data:
  tls.crt: {{ $item.crt }}
  tls.key: {{ $item.key }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
