apiVersion: v1
kind: Service
metadata:
  name: {{ include "hm-basic-webapp.prefix" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
  selector:
    app: {{ include "hm-basic-webapp.prefix" . }}
  type: ClusterIP
