apiVersion: v1
kind: Service
metadata:
  name: {{ include "hm-basic-webapp.prefix" . }}
  labels: {{ toYaml .Values.serviceLabels | nindent 8 }}
spec:
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ include "hm-basic-webapp.prefix" . }}
  type: ClusterIP
