apiVersion: v2
name: sample-app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: hm-worker
  version: 1.4.1
  repository: file://../../../hm-worker
