hm-worker:
  image:
    repository: sample-app
  imagePullSecrets:
    - name: regcred

  ci:
    deploymentTag: worker

  environmentName: develop

  headlessService: true

  metrics:
    enabled: false
    port: 2002

  migration:
    enabled: true
    command:
      - ruby
      - migration.rb

  secretName: sample-app
  deploymentAnnotations:
    foo: bar
    bar: baz

### Config Map
  configMapData:
    BASIC_ENV_A: 'BASIC_A'
    BASIC_ENV_B: 'BASIC_B'
