hm-worker:
  image:
    repository: busybox
  imagePullSecrets:
    - name: regcred

  ci:
    deploymentTag: latest

  environmentName: develop

  headlessService: true

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 40

  metrics:
    enabled: false
    port: 2002

  migration:
    enabled: false
    command:
      - ruby
      - migration.rb

### Config Map
  configMapData:
    BASIC_ENV_A: 'BASIC_A'
    BASIC_ENV_B: 'BASIC_B'

### Secret
  secretData:
    SECRET_ENV_A: 'SECRET_A'
    SECRET_ENV_B: 'SECRET_B'
