apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hm-worker.secretName" . }}
data:
  {{- range $name, $value := .Values.secretData }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}

